build: false
image: Visual Studio 2015
platform:
- x86
- x64
environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
  matrix:
    - CONDA: 27
    - CONDA: 35
install:
- cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
- ps: |
    if ($env:CONDA -eq "27") { $env:CONDA = "" }
    if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
    $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
    $env:CONDA_PREFIX = "C:\Miniconda$env:CONDA"
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    conda info -a
    conda install -c conda-forge conda-build numpy setuptools autograd pybind11 pytest<3.2
build_script:
- ps: python setup.py install
test_script:
- ps: pytest -v
