sudo: false
language: c
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - cmake

env:
    global:
        - EIGEN_VERSION=3.2.9
          TEST_LANG='python'
          CXX=g++-4.8
          CC=gcc-4.8

matrix:
    include:

        # This build will compile the LaTeX source of the paper
        - os: linux
          env: TEST_LANG='paper'

        # This one will test the C++ API
        - os: linux
          env: TEST_LANG='cpp'

        # Linux, Python 2.7
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.9
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.11
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12

        # Linux, Python 3.4
        - os: linux
          env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.9
        - os: linux
          env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.10
        - os: linux
          env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.11

        # Linux, Python 3.5
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.9
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.10
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.11
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.12

install:
    - source .ci/travis.sh

script: |
    if [[ $TEST_LANG == paper ]]
    then
      source .ci/build-paper.sh
    elif [[ $TEST_LANG == cpp ]]
    then
      cd cpp
      CTEST_OUTPUT_ON_FAILURE=1 make test
    elif [[ $TEST_LANG == python ]]
    then
      py.test -v
    fi
